AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Layout/LineLength:
  Enabled: false
  
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
